// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AlertStateAlertKind.
const (
	Breach AlertStateAlertKind = "breach"
	Burn   AlertStateAlertKind = "burn"
)

// Valid indicates whether the value is a known member of the AlertStateAlertKind enum.
func (e AlertStateAlertKind) Valid() bool {
	switch e {
	case Breach:
		return true
	case Burn:
		return true
	default:
		return false
	}
}

// Defines values for BurnEventEventType.
const (
	BurnContinued        BurnEventEventType = "burn_continued"
	BurnResolved         BurnEventEventType = "burn_resolved"
	BurnStarted          BurnEventEventType = "burn_started"
	ErrorBudgetExhausted BurnEventEventType = "error_budget_exhausted"
	ErrorBudgetRecovered BurnEventEventType = "error_budget_recovered"
)

// Valid indicates whether the value is a known member of the BurnEventEventType enum.
func (e BurnEventEventType) Valid() bool {
	switch e {
	case BurnContinued:
		return true
	case BurnResolved:
		return true
	case BurnStarted:
		return true
	case ErrorBudgetExhausted:
		return true
	case ErrorBudgetRecovered:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Ok HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ReadyResponseStatus.
const (
	Ready ReadyResponseStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReadyResponseStatus enum.
func (e ReadyResponseStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for SLORuntimeDatasourceType.
const (
	Clickhouse SLORuntimeDatasourceType = "clickhouse"
	Prometheus SLORuntimeDatasourceType = "prometheus"
)

// Valid indicates whether the value is a known member of the SLORuntimeDatasourceType enum.
func (e SLORuntimeDatasourceType) Valid() bool {
	switch e {
	case Clickhouse:
		return true
	case Prometheus:
		return true
	default:
		return false
	}
}

// Defines values for SLORuntimeType.
const (
	ErrorRate SLORuntimeType = "error_rate"
	Latency   SLORuntimeType = "latency"
)

// Valid indicates whether the value is a known member of the SLORuntimeType enum.
func (e SLORuntimeType) Valid() bool {
	switch e {
	case ErrorRate:
		return true
	case Latency:
		return true
	default:
		return false
	}
}

// AlertState defines model for AlertState.
type AlertState struct {
	AlertKind           AlertStateAlertKind `json:"alertKind"`
	GrafanaNamespaceUid string              `json:"grafanaNamespaceUid"`
	GrafanaRuleGroup    string              `json:"grafanaRuleGroup"`
	GrafanaRuleUid      string              `json:"grafanaRuleUid"`
	LastAppliedSpecHash string              `json:"lastAppliedSpecHash"`
	LastError           *string             `json:"lastError,omitempty"`
	LastReconciledAt    *time.Time          `json:"lastReconciledAt,omitempty"`
	SloId               openapi_types.UUID  `json:"sloId"`
	Status              string              `json:"status"`
}

// AlertStateAlertKind defines model for AlertState.AlertKind.
type AlertStateAlertKind string

// AlertStateListResponse defines model for AlertStateListResponse.
type AlertStateListResponse struct {
	Items []AlertState `json:"items"`
}

// BurnEvent defines model for BurnEvent.
type BurnEvent struct {
	EventType      BurnEventEventType `json:"eventType"`
	Id             openapi_types.UUID `json:"id"`
	IdempotencyKey string             `json:"idempotencyKey"`
	ObservedAt     time.Time          `json:"observedAt"`
	ServiceId      openapi_types.UUID `json:"serviceId"`
	SloId          openapi_types.UUID `json:"sloId"`
	Source         string             `json:"source"`
	Threshold      float32            `json:"threshold"`
	Value          float32            `json:"value"`
}

// BurnEventEventType defines model for BurnEvent.EventType.
type BurnEventEventType string

// BurnEventListResponse defines model for BurnEventListResponse.
type BurnEventListResponse struct {
	Items []BurnEvent `json:"items"`
	Page  Pagination  `json:"page"`
}

// CreateSLORequest defines model for CreateSLORequest.
type CreateSLORequest struct {
	Openslo   string             `json:"openslo"`
	ServiceId openapi_types.UUID `json:"serviceId"`
}

// CreateServiceRequest defines model for CreateServiceRequest.
type CreateServiceRequest struct {
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Name        string                  `json:"name"`
	OwnerTeamId openapi_types.UUID      `json:"ownerTeamId"`
	Slug        string                  `json:"slug"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// Pagination defines model for Pagination.
type Pagination struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
	Total    int `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	Code                 string                 `json:"code"`
	Detail               string                 `json:"detail"`
	Instance             *string                `json:"instance,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ReadyResponse defines model for ReadyResponse.
type ReadyResponse struct {
	Status ReadyResponseStatus `json:"status"`
}

// ReadyResponseStatus defines model for ReadyResponse.Status.
type ReadyResponseStatus string

// SLO defines model for SLO.
type SLO struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Openslo   string             `json:"openslo"`
	Runtime   SLORuntime         `json:"runtime"`
	ServiceId openapi_types.UUID `json:"serviceId"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// SLOListResponse defines model for SLOListResponse.
type SLOListResponse struct {
	Items []SLO      `json:"items"`
	Page  Pagination `json:"page"`
}

// SLORuntime defines model for SLORuntime.
type SLORuntime struct {
	DatasourceType SLORuntimeDatasourceType `json:"datasourceType"`
	DatasourceUid  string                   `json:"datasourceUid"`
	Description    *string                  `json:"description,omitempty"`
	Name           string                   `json:"name"`
	Route          string                   `json:"route"`
	Target         float32                  `json:"target"`
	Threshold      float32                  `json:"threshold"`
	Type           SLORuntimeType           `json:"type"`
	UserExperience *string                  `json:"userExperience,omitempty"`
	WindowMinutes  int                      `json:"windowMinutes"`
}

// SLORuntimeDatasourceType defines model for SLORuntime.DatasourceType.
type SLORuntimeDatasourceType string

// SLORuntimeType defines model for SLORuntime.Type.
type SLORuntimeType string

// Service defines model for Service.
type Service struct {
	CreatedAt   time.Time               `json:"createdAt"`
	Id          openapi_types.UUID      `json:"id"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Name        string                  `json:"name"`
	OwnerTeamId openapi_types.UUID      `json:"ownerTeamId"`
	Slug        string                  `json:"slug"`
	UpdatedAt   time.Time               `json:"updatedAt"`
}

// ServiceListResponse defines model for ServiceListResponse.
type ServiceListResponse struct {
	Items []Service  `json:"items"`
	Page  Pagination `json:"page"`
}

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// TeamListResponse defines model for TeamListResponse.
type TeamListResponse struct {
	Items []Team     `json:"items"`
	Page  Pagination `json:"page"`
}

// UpdateSLORequest defines model for UpdateSLORequest.
type UpdateSLORequest struct {
	Openslo string `json:"openslo"`
}

// UpdateServiceRequest defines model for UpdateServiceRequest.
type UpdateServiceRequest struct {
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Name        string                  `json:"name"`
	OwnerTeamId openapi_types.UUID      `json:"ownerTeamId"`
	Slug        string                  `json:"slug"`
}

// UpdateTeamRequest defines model for UpdateTeamRequest.
type UpdateTeamRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ServiceId defines model for ServiceId.
type ServiceId = openapi_types.UUID

// SloId defines model for SloId.
type SloId = openapi_types.UUID

// TeamId defines model for TeamId.
type TeamId = openapi_types.UUID

// ProblemResponse defines model for ProblemResponse.
type ProblemResponse = Problem

// ListBurnEventsParams defines parameters for ListBurnEvents.
type ListBurnEventsParams struct {
	Page      *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *PageSize           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	ServiceId *openapi_types.UUID `form:"serviceId,omitempty" json:"serviceId,omitempty"`
	SloId     *openapi_types.UUID `form:"sloId,omitempty" json:"sloId,omitempty"`
	From      *time.Time          `form:"from,omitempty" json:"from,omitempty"`
	To        *time.Time          `form:"to,omitempty" json:"to,omitempty"`
}

// ListServicesParams defines parameters for ListServices.
type ListServicesParams struct {
	Page        *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize    *PageSize           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	OwnerTeamId *openapi_types.UUID `form:"ownerTeamId,omitempty" json:"ownerTeamId,omitempty"`
}

// ListSLOsParams defines parameters for ListSLOs.
type ListSLOsParams struct {
	Page      *Page               `form:"page,omitempty" json:"page,omitempty"`
	PageSize  *PageSize           `form:"pageSize,omitempty" json:"pageSize,omitempty"`
	ServiceId *openapi_types.UUID `form:"serviceId,omitempty" json:"serviceId,omitempty"`
}

// CreateSLOParams defines parameters for CreateSLO.
type CreateSLOParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// UpdateSLOParams defines parameters for UpdateSLO.
type UpdateSLOParams struct {
	IdempotencyKey *IdempotencyKey `json:"Idempotency-Key,omitempty"`
}

// ListTeamsParams defines parameters for ListTeams.
type ListTeamsParams struct {
	Page     *Page     `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CreateServiceJSONRequestBody defines body for CreateService for application/json ContentType.
type CreateServiceJSONRequestBody = CreateServiceRequest

// UpdateServiceJSONRequestBody defines body for UpdateService for application/json ContentType.
type UpdateServiceJSONRequestBody = UpdateServiceRequest

// CreateSLOJSONRequestBody defines body for CreateSLO for application/json ContentType.
type CreateSLOJSONRequestBody = CreateSLORequest

// UpdateSLOJSONRequestBody defines body for UpdateSLO for application/json ContentType.
type UpdateSLOJSONRequestBody = UpdateSLORequest

// CreateTeamJSONRequestBody defines body for CreateTeam for application/json ContentType.
type CreateTeamJSONRequestBody = CreateTeamRequest

// UpdateTeamJSONRequestBody defines body for UpdateTeam for application/json ContentType.
type UpdateTeamJSONRequestBody = UpdateTeamRequest

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["detail"], err = json.Marshal(a.Detail)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'detail': %w", err)
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /ready)
	GetReady(w http.ResponseWriter, r *http.Request)

	// (GET /v1/burn-events)
	ListBurnEvents(w http.ResponseWriter, r *http.Request, params ListBurnEventsParams)

	// (GET /v1/services)
	ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams)

	// (POST /v1/services)
	CreateService(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/services/{serviceId})
	DeleteService(w http.ResponseWriter, r *http.Request, serviceId ServiceId)

	// (GET /v1/services/{serviceId})
	GetService(w http.ResponseWriter, r *http.Request, serviceId ServiceId)

	// (PUT /v1/services/{serviceId})
	UpdateService(w http.ResponseWriter, r *http.Request, serviceId ServiceId)

	// (GET /v1/slos)
	ListSLOs(w http.ResponseWriter, r *http.Request, params ListSLOsParams)

	// (POST /v1/slos)
	CreateSLO(w http.ResponseWriter, r *http.Request, params CreateSLOParams)

	// (DELETE /v1/slos/{sloId})
	DeleteSLO(w http.ResponseWriter, r *http.Request, sloId SloId)

	// (GET /v1/slos/{sloId})
	GetSLO(w http.ResponseWriter, r *http.Request, sloId SloId)

	// (PUT /v1/slos/{sloId})
	UpdateSLO(w http.ResponseWriter, r *http.Request, sloId SloId, params UpdateSLOParams)

	// (GET /v1/slos/{sloId}/alert-status)
	GetSLOAlertStatus(w http.ResponseWriter, r *http.Request, sloId SloId)

	// (GET /v1/teams)
	ListTeams(w http.ResponseWriter, r *http.Request, params ListTeamsParams)

	// (POST /v1/teams)
	CreateTeam(w http.ResponseWriter, r *http.Request)

	// (DELETE /v1/teams/{teamId})
	DeleteTeam(w http.ResponseWriter, r *http.Request, teamId TeamId)

	// (GET /v1/teams/{teamId})
	GetTeam(w http.ResponseWriter, r *http.Request, teamId TeamId)

	// (PUT /v1/teams/{teamId})
	UpdateTeam(w http.ResponseWriter, r *http.Request, teamId TeamId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /ready)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/burn-events)
func (_ Unimplemented) ListBurnEvents(w http.ResponseWriter, r *http.Request, params ListBurnEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/services)
func (_ Unimplemented) ListServices(w http.ResponseWriter, r *http.Request, params ListServicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/services)
func (_ Unimplemented) CreateService(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /v1/services/{serviceId})
func (_ Unimplemented) DeleteService(w http.ResponseWriter, r *http.Request, serviceId ServiceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/services/{serviceId})
func (_ Unimplemented) GetService(w http.ResponseWriter, r *http.Request, serviceId ServiceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /v1/services/{serviceId})
func (_ Unimplemented) UpdateService(w http.ResponseWriter, r *http.Request, serviceId ServiceId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/slos)
func (_ Unimplemented) ListSLOs(w http.ResponseWriter, r *http.Request, params ListSLOsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/slos)
func (_ Unimplemented) CreateSLO(w http.ResponseWriter, r *http.Request, params CreateSLOParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /v1/slos/{sloId})
func (_ Unimplemented) DeleteSLO(w http.ResponseWriter, r *http.Request, sloId SloId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/slos/{sloId})
func (_ Unimplemented) GetSLO(w http.ResponseWriter, r *http.Request, sloId SloId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /v1/slos/{sloId})
func (_ Unimplemented) UpdateSLO(w http.ResponseWriter, r *http.Request, sloId SloId, params UpdateSLOParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/slos/{sloId}/alert-status)
func (_ Unimplemented) GetSLOAlertStatus(w http.ResponseWriter, r *http.Request, sloId SloId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/teams)
func (_ Unimplemented) ListTeams(w http.ResponseWriter, r *http.Request, params ListTeamsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /v1/teams)
func (_ Unimplemented) CreateTeam(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /v1/teams/{teamId})
func (_ Unimplemented) DeleteTeam(w http.ResponseWriter, r *http.Request, teamId TeamId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /v1/teams/{teamId})
func (_ Unimplemented) GetTeam(w http.ResponseWriter, r *http.Request, teamId TeamId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (PUT /v1/teams/{teamId})
func (_ Unimplemented) UpdateTeam(w http.ResponseWriter, r *http.Request, teamId TeamId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBurnEvents operation middleware
func (siw *ServerInterfaceWrapper) ListBurnEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBurnEventsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "serviceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "serviceId", r.URL.Query(), &params.ServiceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	// ------------- Optional query parameter "sloId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sloId", r.URL.Query(), &params.SloId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sloId", Err: err})
		return
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBurnEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListServices operation middleware
func (siw *ServerInterfaceWrapper) ListServices(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServicesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "ownerTeamId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ownerTeamId", r.URL.Query(), &params.OwnerTeamId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ownerTeamId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListServices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateService operation middleware
func (siw *ServerInterfaceWrapper) CreateService(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateService(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteService operation middleware
func (siw *ServerInterfaceWrapper) DeleteService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceId" -------------
	var serviceId ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceId" -------------
	var serviceId ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateService operation middleware
func (siw *ServerInterfaceWrapper) UpdateService(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "serviceId" -------------
	var serviceId ServiceId

	err = runtime.BindStyledParameterWithOptions("simple", "serviceId", chi.URLParam(r, "serviceId"), &serviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateService(w, r, serviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSLOs operation middleware
func (siw *ServerInterfaceWrapper) ListSLOs(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSLOsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	// ------------- Optional query parameter "serviceId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "serviceId", r.URL.Query(), &params.ServiceId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "serviceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSLOs(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSLO operation middleware
func (siw *ServerInterfaceWrapper) CreateSLO(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSLOParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSLO(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSLO operation middleware
func (siw *ServerInterfaceWrapper) DeleteSLO(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sloId" -------------
	var sloId SloId

	err = runtime.BindStyledParameterWithOptions("simple", "sloId", chi.URLParam(r, "sloId"), &sloId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sloId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSLO(w, r, sloId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSLO operation middleware
func (siw *ServerInterfaceWrapper) GetSLO(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sloId" -------------
	var sloId SloId

	err = runtime.BindStyledParameterWithOptions("simple", "sloId", chi.URLParam(r, "sloId"), &sloId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sloId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSLO(w, r, sloId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSLO operation middleware
func (siw *ServerInterfaceWrapper) UpdateSLO(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sloId" -------------
	var sloId SloId

	err = runtime.BindStyledParameterWithOptions("simple", "sloId", chi.URLParam(r, "sloId"), &sloId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sloId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateSLOParams

	headers := r.Header

	// ------------- Optional header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = &IdempotencyKey

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSLO(w, r, sloId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSLOAlertStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSLOAlertStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sloId" -------------
	var sloId SloId

	err = runtime.BindStyledParameterWithOptions("simple", "sloId", chi.URLParam(r, "sloId"), &sloId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sloId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSLOAlertStatus(w, r, sloId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTeams operation middleware
func (siw *ServerInterfaceWrapper) ListTeams(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTeamsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "pageSize" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "pageSize", r.URL.Query(), &params.PageSize, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "pageSize", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTeams(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTeam operation middleware
func (siw *ServerInterfaceWrapper) CreateTeam(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTeam(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTeam operation middleware
func (siw *ServerInterfaceWrapper) DeleteTeam(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", chi.URLParam(r, "teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "teamId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTeam(w, r, teamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTeam operation middleware
func (siw *ServerInterfaceWrapper) GetTeam(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", chi.URLParam(r, "teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "teamId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTeam(w, r, teamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTeam operation middleware
func (siw *ServerInterfaceWrapper) UpdateTeam(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", chi.URLParam(r, "teamId"), &teamId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "teamId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTeam(w, r, teamId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ready", wrapper.GetReady)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/burn-events", wrapper.ListBurnEvents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/services", wrapper.ListServices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/services", wrapper.CreateService)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/services/{serviceId}", wrapper.DeleteService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/services/{serviceId}", wrapper.GetService)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/services/{serviceId}", wrapper.UpdateService)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/slos", wrapper.ListSLOs)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/slos", wrapper.CreateSLO)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/slos/{sloId}", wrapper.DeleteSLO)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/slos/{sloId}", wrapper.GetSLO)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/slos/{sloId}", wrapper.UpdateSLO)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/slos/{sloId}/alert-status", wrapper.GetSLOAlertStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/teams", wrapper.ListTeams)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/teams", wrapper.CreateTeam)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/teams/{teamId}", wrapper.DeleteTeam)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/teams/{teamId}", wrapper.GetTeam)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/v1/teams/{teamId}", wrapper.UpdateTeam)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbX2/bOBL/KgLv3k6JnW4XyPktu1fsFuu7BHH3qRcUtDS22EqkSlJuc4G/+4Gk/lAS",
	"9S+xnaTYt1ikZjgzv5n5kVQeUMCSlFGgUqDFA0oxxwlI4PrX+xCSlEmgwf0fcK+eEIoWKAIcAkc+ojgB",
	"tLCnnal5PhJBBAlWLyT4+xLoVkZocfHm0kcJocXvSx/J+1QJEJITukX7vY9u8BZKRV8z4PeVnlSN2cJD",
	"2OAslmhxoQWTJEv037lYQiVsgZdyV+R/vbL1uFP+z3NfWWIUvJnPB9WtgO9IAO/DUl+KZVSpE+W4jzh8",
	"zQiHEC0kz8DWv2E8wRItUJYRNbPtrlXMunXosafJ/wA46VQgzeBTNOzVyyJlVIBG3A1n6xiS2/yZehQw",
	"KoFK9SdO05gEWBJGZ6mZ+Y/PglE1Vun8O4cNWqC/zSpoz8yomOXyjeYQRMBJqsShRaHaC0FiEguvWNe5",
	"dkQuQMm/ioHLlcRSLw+HIVEScHzDWQpcEmXJBscCfJRajx4QVi/+Qaj2J1CFno9onXGKfLTmgIMI3bVc",
	"5KMtxxtM8X9wAiLFAfxJtICuebdZDL9xlqVDk7rkxFjIK+VpCFcpBL9jEXXOe8c5452jtxAwGpAYwitZ",
	"Q0OIJZxJkgBy2CsKTA+Ax0dCYpkJh/q9jcmPZSZUAWg5wu1mh1NLrW5HVQFk688QSLXMCjBLopxSYXsC",
	"eIiEpP5HH84tjO7LFWHO8X3LOUaea92/ZJy+2xW5N36poN75oKXVcf5JSMwlKL/qnyq1Cc2qBxwEi3f6",
	"NyhkfVpn4RbkJ/ge4UzI9gCHgO1AWeLKHDIORqTV5lpT2FpV7Ik4tnvAMJbHo55lPADnMmXEQUQsthOb",
	"ZsladSUf7XCcgWOkCQil1W5QRfpUcS1k2RprTipX2fJuL9BOlh8VtFvp4RueMdRI8JZQ3Yk6EioX4zL3",
	"Vw5Ywmp5fQtfMxBT04ulQEXMNLuq2NTFExHYLJlW/AuFPbaY2Y+zJwGJQyxx92uGVbR0GxrSyzFdXmHf",
	"KPCK2IzIzGw7WU3DnXqpuaj6CrqdqiY8zqOPdMyhDXWZ9jvgWEaPzPGq3xddhX1xFP4mlM1brtVYWTxt",
	"JUWJ6NsG+NWmYnCmZBLHtWlz577CtivfDlk7FyPFaWjOewdSrG5kwEJ3mzEU2TlEqJCYdrSnFl+zPUBk",
	"3NHUciZRJSong/VLmjZlpFqcTdtUWuBy1S3g8P5gAOVK2pMwulpeT1xFoMvHJK4ykimNbz08o1rXQBtV",
	"TTCfOZkxZWk4zcwhnlNYV63et3xpK+yI08noi8LEMxAXK1rTrFPt3RDC5rYgiEnwJWKZ0KWMswRkBLVM",
	"sMpOKSXfug5gsLa/dxSWR7ZJzjIJI9RLzLcgcwVl7XcU+Iqh1/h7/8yGH2OsGXa5P+Jq6+dyYiaAv/ue",
	"AifQVaa/ERqyb/8mNJM5Q+s/7HL0/9z2pqzCeX5Zn63tQwMkzXg7AWmy98XUxx+Syh6o0nZT4ElV1kT8",
	"dJU2R9gzVFvlnReD7FNuKY4CuPEQU34/Gb50kJ8BXH9qFxz9DKKxrL6ThHxFf50kHPIkwTj1BzxJ2Ou9",
	"5oaZazr7HudXRiXHgTzbEC6kd3Xz3tsw7knAifC9nO8L31str70QNoRqXwjfwzT01hmnnj7nFOf/peUG",
	"cqGor6cls9i7iTEFJRj5aAdcGL3z84vzebFJwilBC/STfuTrazPtzlmkjz/Unzk1VM7WKawghH4DaQ5I",
	"UONe7M183nMXNu0OrHEE47gKW5IdUBDCCyIIvujISLwVKiq5AXfq2cxsbnuM0XvpY9pS36w7TFETiG2L",
	"j36e/9QltlznrHkR2emD3cVMgebMgKbTGaqhlIfOpjJXN+0f3auppsz0tfjeHzVPHwapua577tq5/viL",
	"4A5h+cXAkwVtOEvccnp7vluYZNNF3R0Ro+7bDdcNtOnnUC9DNejZUCvxV9S0XvCtiknPBr065R+PmWPG",
	"xrWd6I1MTIT02KbsI/XwlJG4UxSOCUcsahcm+bcTIOQvzFTSg1jlvJTZ1xusYkL7lmcvDu1ZlzfzIS+n",
	"5OeqKL81QZ1YlNV7bx/53j+f1gSsUDfScPZQFtm9oScxmAOjOhL+pZ/bSKiF4m2b2hSOMxILx709mCF+",
	"ZyPvXOX8lIDZsIwew+ppBbH6tkuVpjRzeKy2lzlSkjv3S6OS/KQxy/faP0ySx2ygzy6vXx29O2qHbVyL",
	"jOquyomNzqr8PthVl9eTXd/4xtX44mgtuTpvOXU7Xl47s3R5/crbsMGFlZ2zB70tGdN6NVxGtF19UnDI",
	"lluAubPdulY2PwUYDtliy5Sd1l71pnKotb7cTG+drJ66J3cH93X34s5Mn+nves+qjy960qr8MFZ/DXK0",
	"IHR88uuIi57p8fxLaaKVecYUfW6JqeqGLyIjc9frk9ReDvRBzzg+CTomb2ndAo0iLto3deZi3DVEXfQ9",
	"0DGph30HcGLuYe642u5Tzw/EPp5YW4oY2QifPZj/bxlBJMrgDTEJbfFBqUSFrq6i517c/DTRPSCdsPJo",
	"UlnJTxwHCMUR8699B3diRtAboVfNCcq8zT8eLCDRuM5iAY69EHYQszRR7vRRxmO0QJGU6WI2i9WEiAm5",
	"uJxfzjVUcg3FDWhx56Pak/Xfb8J+UB4W2M9Ux7V+2+f3+7v9/wMAAP//9cE4tH85AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
